### ISSUE TITLE
You may actually allow for an enumeration attack by HTTP status code

### ISSUE THREAD

**Issue by nerdachse** [KJHJason/Blog#3]
Hey there!

I just had a quick glance, but to me it seems like you do indeed allow for an enumeration attack by HTTP status core, although you wanted to avoid it by using the same error message as with an actual wrong username and or password.

https://github.com/KJHJason/Blog/blob/b6116a1883734154cd62cc6424d4ac642d483bbc/api/src/model/auth.rs#L59

Ignore my comment if that's totally intended, I just wanted to help!

**Comment by KJHJason** [comment]
Thanks for pointing it out, I must have been brain dead coding late at night and accepting GitHub Copilot suggestions without checking twice 😂

**Comment by KJHJason** [comment]
Also what brought you here to my repo 👀

**Comment by nerdachse** [comment]
> Also what brought you here to my repo 👀

reverse search for a dependency ;) and then I had to have a look!

Happy hacking!
